# Generated by Django 6.0.6 on 2026-06-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
