# Generated by Django 6.0.6 on 2026-06-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_depositos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositos',
            name='localizacao',
            field=models.CharField(max_length=100),
        ),
    ]
