# Generated by Django 5.2 on 2026-06-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositos',
            name='responsavel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
