# Generated by Django 5.2 on 2026-06-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_alter_depositos_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositos',
            name='responsavel',
        ),
    ]
