# Generated by Django 6.0.6 on 2026-07-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_alter_categoria_id_alter_depositos_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('FUNC', 'Funcionário')], max_length=10),
        ),
    ]
