# Generated by Django 6.0.6 on 2026-06-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_categoria_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depositos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.TextField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
            ],
        ),
    ]
